export const BRANDS = [
  { value: "Adidas",          label: "أديداس"           },
  { value: "Aldo",            label: "ألدو"              },
  { value: "Armani",          label: "أرماني"            },
  { value: "ASOS",            label: "ASOS"              },
  { value: "Badgley Mischka", label: "بادجلي ميشكا"     },
  { value: "Balenciaga",      label: "بالنسياغا"        },
  { value: "Bershka",         label: "بيرشكا"           },
  { value: "Burberry",        label: "بربري"            },
  { value: "Calvin Klein",    label: "كالفن كلاين"     },
  { value: "Carter's",        label: "كارتر"            },
  { value: "Chanel",          label: "شانيل"            },
  { value: "Champion",        label: "تشامبيون"         },
  { value: "Coast",           label: "كوست"             },
  { value: "Coach",           label: "كوتش"             },
  { value: "Defacto",         label: "ديفاكتو"          },
  { value: "Dior",            label: "ديور"             },
  { value: "DKNY",            label: "DKNY"             },
  { value: "Dune",            label: "ديون"             },
  { value: "Fendi",           label: "فندي"             },
  { value: "Fossil",          label: "فوسيل"            },
  { value: "Gap",             label: "GAP"              },
  { value: "Gizia",           label: "جيزيا"            },
  { value: "Gucci",           label: "غوتشي"            },
  { value: "Guess",           label: "غيس"              },
  { value: "H&M",             label: "H&M"              },
  { value: "Hugo Boss",       label: "هوغو بوس"         },
  { value: "Karen Millen",    label: "كارن ميلن"       },
  { value: "Kate Spade",      label: "كيت سبيد"        },
  { value: "Lacoste",         label: "لاكوست"           },
  { value: "LC Waikiki",      label: "LC Waikiki"       },
  { value: "Levi's",          label: "ليفايز"           },
  { value: "Louis Vuitton",   label: "لويس فيتون"      },
  { value: "Mango",           label: "مانجو"            },
  { value: "Marks & Spencer", label: "ماركس أند سبنسر" },
  { value: "Massimo Dutti",   label: "ماسيمو دوتي"     },
  { value: "Michael Kors",    label: "مايكل كورس"      },
  { value: "Monsoon",         label: "مونسون"           },
  { value: "Mothercare",      label: "مازر كير"         },
  { value: "New Balance",     label: "نيو بالانس"       },
  { value: "Next",            label: "نكست"             },
  { value: "Nike",            label: "نايك"             },
  { value: "Nine West",       label: "ناين ويست"       },
  { value: "Pandora",         label: "باندورا"          },
  { value: "Polo",            label: "بولو"             },
  { value: "Prada",           label: "برادا"            },
  { value: "Pull & Bear",     label: "بول أند بير"     },
  { value: "Puma",            label: "بوما"             },
  { value: "Rado",            label: "رادو"             },
  { value: "Ralph Lauren",    label: "رالف لورن"        },
  { value: "Reebok",          label: "ريبوك"            },
  { value: "River Island",    label: "ريفر أيلاند"     },
  { value: "Sherri Hill",     label: "شيري هيل"         },
  { value: "Steve Madden",    label: "ستيف مادن"        },
  { value: "Stradivarius",    label: "ستراديفاريوس"    },
  { value: "Swarovski",       label: "سواروفسكي"       },
  { value: "Ted Baker",       label: "تيد بيكر"         },
  { value: "Tommy Hilfiger",  label: "تومي هيلفيغر"   },
  { value: "Tory Burch",      label: "توري بيرش"       },
  { value: "Under Armour",    label: "أندر آرمور"      },
  { value: "Valentino",       label: "فالنتينو"         },
  { value: "Versace",         label: "فيرساتشي"         },
  { value: "Zara",            label: "زارا"             },
  { value: "Custom Made",     label: "تفصيل"            },
  { value: "Other",           label: "أخرى"             },
];

/** English value → Arabic display label */
export const BRAND_LABEL: Record<string, string> = Object.fromEntries(
  BRANDS.map((b) => [b.value, b.label])
);

/** Alphabetically sorted by Arabic label, excluding pinned entries */
export const SEARCHABLE_BRANDS = BRANDS
  .filter((b) => b.value !== "Custom Made" && b.value !== "Other")
  .sort((a, b) => a.label.localeCompare(b.label, "ar"));
